### ISSUE TITLE
Entities vs DTOs

### ISSUE THREAD

**Issue by lucianlature** [mmacneil/CleanAspNetCoreWebAPI#1]
Hi @mmacneil 

Great seeing new stuff being added daily.
In fact, I am working on a very similar pet project using TypeScript instead of C#, so your project gives me a really good starting point, cheers.

My questions for you at this point are: 
- why `Token.cs` is listed under `Dto`, but `User.cs` is under `Entities`? I would expect both to be under `Entities`. 
- what's the best definition for `dtos`?

**Comment by mmacneil** [comment]
Hey @lucianlature - great question and one I bump one into regularly myself as I find it's not always initially apparent when trying to model a new concept in a domain whether it should be an `Entity,` `Value` or `Dto.`  

Like everything, there's no definitive answer or checklist one can apply to make that distinguishment but here are a few guidelines you may find useful.

**Identity** - An `Entity` has an Id.  Think of classic examples: `Customer,` `Order,` `Product` etc.  - in any system or model the identity of those things matters.  The Id of an `Address` for a `Customer` or the `Price` of a `Product` usually doesn't so they can be set up as `Value` objects in the domain.  This also directly relates to their equality because entities contain inherent identity we use their `Id` to determine equality, i.e., it's possible we could have two customers with `Name == "John Doe"` but their `Id` distinguishes them as being different.  For values, we typically use their structure to determine equality, i.e., we have two price objects that look like `{ Amount = 4.25, TaxPct = 15 }` but our object model treats them as the same because structurally they are and can be used interchangeably with no impact.  Another way to think about this is that `Value` objects cannot live on their own - they typically always belong to one or more entities.

**Lifespan** - Entities are almost guaranteed to change in the future.  An `Order` will have products added or removed over time, a `Customer` accumulates orders over time and so forth.  We rely on their `Id` to help track these changes to their state over time.  `Value` objects have no lifespan and can be created or destroyed at any point with no impact because they are interchangeable.

**Immutability** - This is directly related to the previous rule.  A value should be immutable, and if we find ourselves needing to mutate it over time (thereby giving it a lifespan), then it is likely not a value at all and should probably be converted to an entity within the model.

*What's the best definition for dtos?*

I think of these as vessels for shuttling data in and out of objects, i.e., the request/response objects in the use cases in this repo OR across boundaries of the application, i.e., a mobile app client sends a `LoginRequestDto` to the rest API.  I try to keep them nice and lightweight (no behavior or serialization details) and based on primitive types or composed of dto types following the same rules.  [Martin Fowler has an excellent description too](https://martinfowler.com/eaaCatalog/dataTransferObject.html)
